# Generated by Django 5.0.7 on 2025-05-20 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='EliminarRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_nombre', models.CharField(max_length=255)),
                ('motivo', models.TextField()),
                ('fecha_eliminacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Herramientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('condicion', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Bueno', 'Bueno'), ('Desgastado', 'Desgastado'), ('Dañado', 'Dañado')], default='Nuevo', max_length=20)),
                ('prestamo', models.BooleanField(blank=True, default=False, null=True)),
                ('cantidad_minima', models.PositiveIntegerField(default=0)),
                ('coordinador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(max_length=250)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('tipo_material', models.CharField(choices=[('prueba', 'prueba'), ('RES', 'RESGUARDOS'), ('HER', 'HERRAMIENTAS'), ('LIM', 'MATERIAL DE LIMPIEZA Y BIOSEGURIDAD'), ('PPL', 'PAPELERIA'), ('ELM', 'ELECTROMECANICA'), ('PLO', 'PLOMERIA'), ('ELE', 'ELECTRICIDAD'), ('CABLE', 'CABLE')], default='FER', max_length=20)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('eliminado', models.BooleanField(blank=True, default=False, null=True)),
                ('cantidad_minima', models.PositiveIntegerField(default=0)),
                ('coordinador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cedula', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=150)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, max_length=150, null=True)),
                ('analista', models.CharField(max_length=150)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=1000)),
                ('tipo', models.CharField(max_length=150)),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.personas')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analista', models.CharField(max_length=150)),
                ('cantidad', models.PositiveBigIntegerField()),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=150)),
                ('herramienta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.herramientas')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.personas')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobada')], default='P', max_length=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.personas')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo_id', models.PositiveIntegerField()),
                ('articulo_solicitado', models.CharField(max_length=150)),
                ('cantidad', models.PositiveIntegerField()),
                ('tipo', models.CharField(max_length=150)),
                ('encargado', models.CharField(blank=True, max_length=150, null=True)),
                ('uso', models.CharField(blank=True, max_length=150, null=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.solicitudes')),
            ],
        ),
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
