# Generated by Django 5.0.7 on 2025-05-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_herramientas_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramientas',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
