# Generated by Django 5.0.7 on 2025-05-28 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_herramientas_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='materialID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.material'),
        ),
    ]
